# Common
dataset_id: unittest
# Feature extraction
utterance_length_ms: 3000
utterance_offset_ms: 1000
sequence_length: 32
extractors:
    - name: mfcc-deltas-012
      n_mfcc: 19
# Model training
model:
    name: debug-lstm
    batch_size: 64
    dataset_shuffle_size: 30
    epochs: 5
    loss: categorical_crossentropy
    metrics:
        - accuracy
    num_cells: 4
    optimizer: adam
    steps_per_epoch: 50
    validation_steps: 10
    verbose: 1
