# Common
dataset_id: unittest
# Feature extraction
utterance_length_ms: 3000
utterance_offset_ms: 1000
sequence_length: 16
print_progress: 10
extractors:
    - name: mfcc-deltas-012
      n_mfcc: 13
# Model training
model:
    name: debug-lstm
    batch_size: 32
    dataset_shuffle_size: 300
    epochs: 25
    loss: categorical_crossentropy
    metrics:
        - accuracy
    num_cells: 8
    optimizer: adam
    steps_per_epoch: 100
    validation_steps: 10
    verbose: 2
