$schema: 'http://json-schema.org/draft-07/schema#'
type: object
description: 'lidbox configuration file'
required:
  - datasets
additionalProperties: false
properties:
  datasets:
    type: array
    minItems: 1
    contains:
      $ref: '#/definitions/dataset'
  user_script:
    $ref: '#/definitions/user_script'
  cache:
    $ref: '#/definitions/cache'
  pre_process:
    $ref: '#/definitions/pre_process'
  features:
    $ref: '#/definitions/features'
  post_process:
    $ref: '#/definitions/post_process'
  show_samples:
    $ref: '#/definitions/show_samples'
  experiment:
    $ref: '#/definitions/experiment'
