$schema: 'http://json-schema.org/draft-07/schema#'
type: object
description: 'lidbox configuration file'
required:
  - datasets
additionalProperties: false
properties:
  datasets:
    type: array
    minItems: 1
    contains:
      $ref: '#/definitions/dataset'
  pre_initialize:
    $ref: '#/definitions/pre_initialize'
  post_initialize:
    $ref: '#/definitions/post_initialize'
  user_script:
    $ref: '#/definitions/user_script'
  pre_process:
    $ref: '#/definitions/pre_process'
  features:
    $ref: '#/definitions/features'
  post_process:
    $ref: '#/definitions/post_process'
  experiment:
    $ref: '#/definitions/experiment'
  embeddings:
    $ref: '#/definitions/embeddings'
